apiVersion: batch/v1
kind: Job

metadata:
  name:  primeiro-job-hello-world-v2

spec:
  completions: 1000
  template:
    metadata:
      name:  primeiro-job-hello-world-v2
    spec:
      restartPolicy: OnFailure
      containers:
        - name: primeiro-job-hello-world-v2-container
          image:  busybox
          command: ["/bin/sh", "-c"]
          args: ["echo 'Hello Wold!'", "sleep 3", "echo 'Chegabdo mais Pods!!'"]
